# -*- coding: utf-8 -*-
"""Alcan_DETR_use.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g6eT3rQ5BWk7IkeZbPDYeFTkVmBRurUj
"""
from plot_utils import plot_logs
import os
from pathlib import Path

def main():
    log_directory = [Path(os.getcwd())]

    fields_of_interest_1 = ('loss', 'mAP')
    plot_logs(log_directory, fields_of_interest_1)

    fields_of_interest_2 = ('loss', 'loss_ce')
    plot_logs(log_directory, fields_of_interest_2)

if __name__ == "__main__":
    main()

